
import { SectionData, SectionKey, ContentBlockQuiz, MCQ, ContentBlockVideo, ContentBlockShortAnswer, InteractiveTerm } from '../types';
import { BookOpenIcon, CogIcon, MegaphoneIcon, CurrencyDollarIcon, UsersIcon, LightBulbIcon, PresentationChartLineIcon, SparklesIcon } from './icons';

// --- Reusable Interactive Terms ---
const termSupplyChain: InteractiveTerm = { type: 'interactiveTerm', term: 'Supply Chain', definition: 'The entire network of organizations, people, activities, information, and resources involved in creating and moving a product or service from suppliers to customers.' };
const termOutsourcing: InteractiveTerm = { type: 'interactiveTerm', term: 'Outsourcing', definition: 'Hiring an external organization to perform services or create goods that were traditionally performed in-house by the company\'s own employees and staff.' };
const termCarbonNeutral: InteractiveTerm = { type: 'interactiveTerm', term: 'Carbon Neutral', definition: 'Achieving net-zero carbon dioxide emissions by balancing carbon emissions with carbon removal or by eliminating carbon emissions altogether.' };
const termEcosystem: InteractiveTerm = { type: 'interactiveTerm', term: 'Ecosystem (Business)', definition: 'A network of interconnected organizations, including suppliers, distributors, customers, competitors, and government agencies, involved in the delivery of a specific product or service through both competition and cooperation.' };
const termMarketingMix: InteractiveTerm = { type: 'interactiveTerm', term: 'Marketing Mix (4Ps)', definition: 'A foundational model in marketing, representing the four key elements of a marketing strategy: Product, Price, Place, and Promotion.' };
const termBranding: InteractiveTerm = { type: 'interactiveTerm', term: 'Branding', definition: 'The process of creating a unique name and image for a product in the consumers\' mind, mainly through advertising campaigns with a consistent theme. Branding aims to establish a significant and differentiated presence in the market that attracts and retains loyal customers.' };
const termPremiumPricing: InteractiveTerm = { type: 'interactiveTerm', term: 'Premium Pricing', definition: 'A strategy where a company sets a higher price for its products compared to competitors, often to convey an image of luxury, high quality, or exclusivity.' };
const termFreemiumPricing: InteractiveTerm = { type: 'interactiveTerm', term: 'Freemium Pricing', definition: 'A business model offering a basic version of a product or service for free, while charging for advanced features, functionality, or related products and services.' };
const termRevenue: InteractiveTerm = { type: 'interactiveTerm', term: 'Revenue', definition: 'The total amount of income generated by the sale of goods or services related to the company\'s primary operations.' };
const termNetIncome: InteractiveTerm = { type: 'interactiveTerm', term: 'Net Income (Profit)', definition: 'A company\'s total earnings (or profit). Net income is calculated by taking revenues and subtracting the costs of doing business such as operating expenses, interest, taxes, and depreciation.' };
const termGrossMargin: InteractiveTerm = { type: 'interactiveTerm', term: 'Gross Margin', definition: 'Represents the percent of total sales revenue that the company retains after incurring the direct costs associated with producing the goods and services sold by a company.' };
const termOperatingExpenses: InteractiveTerm = { type: 'interactiveTerm', term: 'Operating Expenses (OpEx)', definition: 'The costs a business incurs to engage in its normal business activities, such as rent, salaries, utilities, and marketing.' };
const termInflation: InteractiveTerm = { type: 'interactiveTerm', term: 'Inflation', definition: 'The rate at which the general level of prices for goods and services is rising, and consequently, the purchasing power of currency is falling.' };
const termAutocraticLeadership: InteractiveTerm = { type: 'interactiveTerm', term: 'Autocratic Leadership', definition: 'A leadership style characterized by individual control over all decisions and little input from group members. Autocratic leaders typically make choices based on their ideas and judgments and rarely accept advice from followers.' };
const termDemocraticLeadership: InteractiveTerm = { type: 'interactiveTerm', term: 'Democratic Leadership', definition: 'A leadership style in which members of the group take a more participative role in the decision-making process. Everyone is given the opportunity to participate, ideas are exchanged freely, and discussion is encouraged.' };
const termChangeManagement: InteractiveTerm = { type: 'interactiveTerm', term: 'Change Management', definition: 'A systematic approach to dealing with the transition or transformation of an organization\'s goals, processes or technologies. The purpose is to implement strategies for effecting change, controlling change and helping people to adapt to change.' };
const termExternalInfluences: InteractiveTerm = { type: 'interactiveTerm', term: 'External Influences', definition: 'Factors outside of a business that can affect its performance and decision-making. These can include economic, social, technological, environmental, political, legal, and ethical factors.' };
const termInputs: InteractiveTerm = { type: 'interactiveTerm', term: 'Inputs', definition: 'The resources (such as raw materials, labor, components, and capital) that are used to produce goods or services.' };
const termTransformationProcess: InteractiveTerm = { type: 'interactiveTerm', term: 'Transformation Process', definition: 'The set of activities that convert inputs into outputs (goods or services). This involves adding value to the inputs.' };
const termOutputs: InteractiveTerm = { type: 'interactiveTerm', term: 'Outputs', definition: 'The final goods or services produced by a business through its transformation process.' };
const termEthicalSourcing: InteractiveTerm = { type: 'interactiveTerm', term: 'Ethical Sourcing', definition: 'The process of ensuring that the products being sourced are obtained in a responsible and sustainable way, that the workers involved are safe and treated fairly and that environmental and social impacts are taken into account.' };
const termStakeholder: InteractiveTerm = { type: 'interactiveTerm', term: 'Stakeholder', definition: 'Any individual, group, or organization that can affect or is affected by an organization\'s actions, objectives, and policies. Examples include customers, employees, investors, suppliers, and the community.' };

// --- Video Specific Content Blocks ---
const operationsVideoSpecificMCQs: MCQ[] = [
  { id: 'op_vid_mcq1', question: "According to general knowledge about Apple's supply chain, what is a primary role of a company like Foxconn in Apple's production process?", options: ["Designing Apple's software", "Assembling iPhones and other devices", "Marketing Apple products globally", "Sourcing all raw materials"], correctAnswerIndex: 1, explanation: "Foxconn is a major manufacturing partner responsible for the large-scale assembly of many Apple products." },
  { id: 'op_vid_mcq2', question: "Apple's supply chain is often described as 'global'. What does this primarily imply?", options: ["All products are sold in every country.", "Components are sourced and products are assembled in various countries worldwide.", "Apple Stores are present in every major city.", "Marketing campaigns are identical across all regions."], correctAnswerIndex: 1, explanation: "A global supply chain means that different stages, from sourcing materials to manufacturing and assembly, occur across multiple countries." },
  { id: 'op_vid_mcq3', question: "What is a significant logistical consideration for Apple when launching a new product globally, as suggested by the complexity of its supply chain?", options: ["Ensuring all retail staff are trained on the same day.", "Designing the product packaging.", "Coordinating mass production and worldwide distribution to meet high initial demand.", "Choosing the color options for the new product."], correctAnswerIndex: 2, explanation: "Meeting the massive global demand for new products like iPhones requires intricate planning of production schedules and complex logistics to ship units worldwide simultaneously." }
];
const operationsVideoQuizBlock: ContentBlockQuiz = { type: 'quiz', title: 'Video Checkpoint: Apple Supply Chain Insights', mcqs: operationsVideoSpecificMCQs };

const marketingVideoBlock: ContentBlockVideo = { type: 'video', youtubeId: '9f9eW739yCg', title: "Apple's Marketing Strategies Explained" };
const marketingVideoMCQs: MCQ[] = [
  { id: 'mk_vid_mcq1', question: "What are the two main pricing strategies Apple uses, according to the video?", options: [ "Discount Pricing & Competitive Pricing", "Premium Pricing & Freemium Pricing", "Cost-Plus Pricing & Value-Based Pricing", "Bundle Pricing & Psychological Pricing"], correctAnswerIndex: 1, explanation: "The video explicitly mentions 'Premium pricing strategies' and 'Freemium pricing strategy' (0:18-1:24)." },
  { id: 'mk_vid_mcq2', question: "Which Apple service is highlighted in the video as an example of the 'freemium' pricing strategy?", options: [ "Apple Music subscription", "iPhone purchase", "iCloud storage (5GB free, pay for more)", "Apple TV+ subscription" ], correctAnswerIndex: 2, explanation: "The video states, 'For example, the brand gives 5 GB of iCloud storage for free. But users have to pay an additional fee if they want more storage' (1:54-2:04)." },
  { id: 'mk_vid_mcq3', question: "According to the video, how does Apple create 'mystery around products' as a marketing tactic?", options: [ "By announcing products years in advance", "By leaking all product details through tech blogs", "By not revealing much about the details and features of its new products", "By offering large pre-order discounts" ], correctAnswerIndex: 2, explanation: "The video explains, 'Apple doesn't reveal much about the details and features of its new products. This way, people get excited about the product' (2:50-3:01)." },
  { id: 'mk_vid_mcq4', question: "What key benefit of 'Keeping Your Branding Consistent' is mentioned in the video?", options: ["It allows for frequent logo changes.", "It makes products cheaper to produce.", "People recognize the brand even before seeing the logo.", "It simplifies employee training."], correctAnswerIndex: 2, explanation: "The video states, 'When you see an ad for Apple, you know who they are even before you see their logo. Branding has that kind of power.' (3:06-3:13)." }
];
const marketingVideoQuizBlock: ContentBlockQuiz = { type: 'quiz', title: 'Video Checkpoint: Understanding Apple\'s Marketing', mcqs: marketingVideoMCQs };
const marketingVideoShortAnswers: ContentBlockShortAnswer = {
  type: 'shortAnswer', title: "Video Reflection: Deeper Dive into Marketing Techniques",
  prompts: [
    { id: 'mk_vid_sa1', prompt: "Based on the video, explain Apple's 'premium pricing' strategy and provide an example it discusses." },
    { id: 'mk_vid_sa2', prompt: "The video mentions 'Help Your Customer’s Share Your Values.' How does Apple achieve this, and what is the suggested impact on customers?" },
    { id: 'mk_vid_sa3', prompt: "Describe two specific communication techniques Apple uses in its advertising or on its product pages, as highlighted in the video (e.g., simplicity, speaking the audience's language)." }
  ]
};

export const studySectionsData: SectionData[] = [
  {
    id: SectionKey.INTRODUCTION,
    title: "Introduction to Business Management Task",
    summary: "Overview of the assessment task focusing on Apple's management of change, and key business concepts.",
    icon: BookOpenIcon,
    detailedContent: [
      { type: 'heading', text: "Understanding the Assessment Task" },
      { type: 'paragraph', text: ["The business world is in a constant state of flux, with numerous ", termExternalInfluences, " compelling companies to adapt and evolve. This assessment task challenges you to explore how Apple Inc., a global technology leader, has navigated recent significant changes. Your primary focus will be on ", termChangeManagement, ", examining how various shifts have impacted Apple's four key business functions (Operations, Marketing, Finance, and Human Resources) and how the company has strategically responded."] },
      { type: 'subheading', text: "Key External Influences Impacting Businesses:" },
      { type: 'list', items: [
        ["Rapid advancements in technology, including innovations in hardware, software, ", {type: 'interactiveTerm', term: 'cybersecurity', definition: 'The practice of protecting systems, networks, and programs from digital attacks, usually aimed at accessing, changing, or destroying sensitive information, extorting money from users, or interrupting normal business processes.'}, ", and ", {type: 'interactiveTerm', term: 'Artificial Intelligence (AI)', definition: 'The simulation of human intelligence processes by machines, especially computer systems. These processes include learning, reasoning, and self-correction.'}, "."],
        ["Fluctuations in the price of raw materials, often linked to ", termInflation, " and global ", termSupplyChain, " dynamics."],
        ["Broad economic challenges affecting consumers, such as increased cost of living and changes in ", {type: 'interactiveTerm', term: 'disposable income', definition: 'Income remaining after deduction of taxes and social security charges, available to be spent or saved as one wishes.'}, "."],
        ["Evolving ", {type: 'interactiveTerm', term: 'consumer tastes and preferences', definition: 'The desires, expectations, and choices of customers regarding products and services, which can change over time due to trends, cultural shifts, or new information.'}, ", demanding new features, designs, or service models."],
        ["Growing societal awareness and concern regarding environmental sustainability and ", {type: 'interactiveTerm', term: 'climate change', definition: 'Long-term shifts in temperatures and weather patterns, primarily caused by human activities, especially the burning of fossil fuels.'}, "."]
      ]},
      { type: 'paragraph', text: "This study guide is designed to equip you with the foundational knowledge and analytical frameworks needed to prepare comprehensive research notes. These notes will be crucial for the subsequent in-class short answer questions, where you will demonstrate your understanding of Apple's strategic responses to these dynamic influences."}
    ],
  },
  {
    id: SectionKey.OPERATIONS,
    title: "Operations Management at Apple",
    summary: "Exploring Apple's operational strategies, including outsourcing, supply chain management, ethical considerations, its shift to an ecosystem model, and sustainability initiatives.",
    icon: CogIcon,
    detailedContent: [
      { type: 'heading', text: ["Strategic Shift: ", termOutsourcing, " Manufacturing"] as (string | InteractiveTerm)[] },
      { type: 'paragraph', text: ["A pivotal change in Apple's operations occurred in 2001 when the company began to outsource a significant portion of its manufacturing, notably to Foxconn, a large electronics manufacturing company based in China. This strategic move allowed Apple to concentrate its resources on its core competencies: innovative product design, software development, and powerful ", termBranding, " and marketing campaigns, while leveraging Foxconn's expertise in large-scale production."] as (string | InteractiveTerm)[] },
      { type: 'subheading', text: "Key Motivations for Outsourcing:" },
      { type: 'list', items: [
        ["Cost Reduction: Manufacturing in China offered significantly lower labor costs (e.g., $3.50–$5.00 per hour compared to $25-$30 per hour in the U.S. at the time), contributing to higher ", {type: 'interactiveTerm', term: 'profit margins', definition: 'The percentage of revenue that remains after all costs and expenses have been deducted. Higher profit margins generally indicate better financial health and efficiency.'}, "."],
        ["Speed and Efficiency: Foxconn possessed the infrastructure, a vast workforce (over one million employees), and extensive experience to rapidly scale production, crucial for meeting the high global demand during new product launches."],
        ["Established ", termSupplyChain, ": China had a highly developed electronics manufacturing ", termEcosystem, ", with suppliers, ", {type: 'interactiveTerm', term: 'logistics', definition: 'The overall process of managing how resources are acquired, stored, and transported to their final destination. It involves planning, implementing, and controlling procedures for the efficient and effective transportation and storage of goods.'}, " providers, and factories located in close proximity. This reduced transportation costs and potential delays."]
      ]},
      { type: 'image', src: 'https://images.unsplash.com/photo-1553775282-20af807797d1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZmFjdG9yeSUyMHdvcmtlcnN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=600&q=60', alt: 'Factory assembly line illustrating manufacturing', caption: 'Modern electronics assembly lines are crucial for high-volume production.' },
      { type: 'subheading', text: ["Impact on Apple's Operations (",termInputs,", ",termTransformationProcess,", and ",termOutputs,")"] as (string | InteractiveTerm)[] },
      { type: 'list', items: [
          ["Reduced Direct Labor ", termInputs, ": Lowered Apple's direct involvement in the physical manufacturing workforce."],
          ["Focus on Design & IP as Key ", termInputs, ": Apple's primary inputs became intellectual property, design specifications, and component sourcing management."],
          ["Shifted ", termTransformationProcess, ": The core transformation of raw materials into finished goods largely moved to partners like Foxconn, managed through Apple's specifications and quality control."],
          ["High-Volume, High-Quality ", termOutputs, ": Enabled the consistent production of millions of devices to meet global demand."],
          ["Faster Time to Market: Apple could bring products from design to global ", termOutputs, " (market availability) more quickly."]
      ]},
      { type: 'heading', text: ["Ethical Considerations in the ", termSupplyChain, " & Apple's Response"] },
      { type: 'paragraph', text: ["The benefits of ", termOutsourcing, " were accompanied by significant ethical concerns regarding labor practices at some supplier factories, including reports of excessive working hours, stressful work environments, low wages, and inadequate living conditions. These issues, highlighted by events like worker suicides at Foxconn in 2010, led to widespread public scrutiny and media coverage, questioning Apple's responsibility as a ", {type: 'interactiveTerm', term: 'global corporation', definition: 'A company that operates in at least one country other than its home country. This includes having offices, factories, or conducting business activities internationally.'}, "."] },
      { type: 'subheading', text: "Apple's Corrective Actions and Ongoing Efforts:" },
      { type: 'list', items: [
        ["Supplier Code of Conduct & Audits: Apple established and enforces a Supplier Code of Conduct, conducting regular audits to monitor compliance with labor laws and ethical standards. This forms part of their ", termEthicalSourcing, " strategy."],
        ["Partnership with the Fair Labor Association (FLA): Apple joined the FLA and commissioned independent assessments of its supply chain, publishing the findings to increase transparency."],
        ["Investments in Supplier Worker Well-being: Initiatives to improve working conditions, reduce overtime, ensure fair wages, and enhance safety protocols and living conditions at supplier facilities."],
        ["Transparency Reports: Apple now publishes annual Supplier Responsibility reports detailing its efforts, progress, and challenges in upholding ethical standards." ]
      ]},
      { type: 'resourceLink', text: "Apple Supplier Responsibility Page", url: "https://www.apple.com/supplier-responsibility/"},
      { type: 'video', youtubeId: '0D9YBgkhGso', title: "Apple Supply Chain Explained"},
      operationsVideoQuizBlock,
      { type: 'heading', text: ["Evolution: From Devices to Integrated ", termEcosystem, " and Sustainability Focus"] },
      { type: 'paragraph', text: ["Operationally, Apple has transitioned from being primarily a product-focused company (e.g., Mac, iPod) to managing a complex global ", termEcosystem, " that seamlessly integrates hardware devices with a vast array of services. This strategic pivot has had profound implications for its operations."] },
      { type: 'paragraph', text: ["Key operational expansions include managing the infrastructure for the App Store (which facilitated $1.1 trillion in billings and sales in 2022 and supports over 370 billion app downloads), and scaling production for wearables like the Apple Watch and AirPods, which have become market leaders. This requires sophisticated ", termSupplyChain, " management to handle diverse product lines and software updates."] },
      { type: 'subheading', text: ["Commitment to Sustainability: ", termCarbonNeutral, " by 2030"] },
      { type: 'paragraph', text: ["Apple has set an ambitious goal to be ", termCarbonNeutral, " across its entire business, manufacturing ", termSupplyChain, ", and product life cycle by 2030. This operational change involves significant efforts such as transitioning suppliers to 100% renewable energy, ", termEthicalSourcing, " of materials (including recycled content), and designing products for increased recyclability and energy efficiency."] },
    ],
    mcqs: [
      { id: 'op_mcq1', question: "What was a primary financial benefit for Apple outsourcing manufacturing to Foxconn?", options: ["Improved product quality", "Access to new markets", "Significant reduction in labor costs", "Enhanced employee morale"], correctAnswerIndex: 2, explanation: "Labor costs in China were substantially lower than in the U.S., which was a major factor in Apple's ability to maintain high profit margins." }
    ],
    matchingActivities: [{
      title: "Operations Key Terms",
      pairs: [
        { id: 'op_m1', term: "Outsourcing", definition: "Contracting manufacturing to a third-party like Foxconn to leverage cost and efficiency benefits." },
        { id: 'op_m2', term: "FLA (Fair Labor Association)", definition: "An organization Apple partnered with for independent inspections of its supplier factories to address ethical concerns." },
        { id: 'op_m3', term: "Carbon Neutral by 2030", definition: "Apple's major sustainability goal, aiming to have a net-zero climate impact across its entire business and supply chain." }
      ]
    }],
    shortAnswerPrompts: [
      { id: 'op_sa1', prompt: "Outline the changes that have impacted Apple’s operations, considering factors like outsourcing, supply chain complexity, and sustainability goals." },
      { id: 'op_sa2', prompt: "Explain how Apple responded to/managed these operational changes. What impact did these changes have on Apple’s inputs, transformation process, and outputs?"},
      { id: 'op_sa3', prompt: "Outline the outcomes and evaluate the effectiveness of Apple in managing and responding to these operational changes. Consider both benefits and challenges."}
    ]
  },
  {
    id: SectionKey.MARKETING,
    title: "Marketing Strategies at Apple",
    summary: "Examining Apple's evolution in marketing, from product-centric approaches to ecosystem and lifestyle branding, its focus on user experience, and innovation-driven campaigns.",
    icon: MegaphoneIcon,
    detailedContent: [
        { type: 'heading', text: ["The Evolution of Apple's ", termBranding, ": From Products to Ecosystems and Lifestyles"] as (string | InteractiveTerm)[] },
        { type: 'paragraph', text: ["Apple's marketing strategy has undergone a significant transformation. Initially focused on promoting individual products, it has evolved to emphasize a comprehensive ", termEcosystem, " and a desirable lifestyle. For instance, the Apple Watch and AirPods are not just marketed as technological gadgets but as fashionable, health-conscious, and premium lifestyle accessories that integrate seamlessly into a user's daily life."] },
        { type: 'subheading', text: ["The App Store: A Secure and Trusted Marketplace"] },
        { type: 'paragraph', text: ["A key component of Apple's marketing is the promotion of the App Store as a secure and trustworthy platform. This is reinforced by strict review guidelines for apps, emphasizing user privacy and security. The success of this approach is evident, with in-app advertising on the platform experiencing significant growth (e.g., 24% in 2022)."] },
        { type: 'image', src: 'https://images.unsplash.com/photo-1605529275880-0e9958a50674?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YXBwbGUlMjBwcm9kdWN0JTIwbGlmZXN0eWxlfGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60', alt: 'Apple product lifestyle shot', caption:'Apple products are often marketed as integral parts of a modern, aspirational lifestyle.' },
        { type: 'subheading', text: ["Emphasis on a Seamless ", {type: 'interactiveTerm', term: 'User Experience (UX)', definition: 'The overall experience a user has when interacting with a product or service, especially in terms of how easy or pleasing it is to use.'}] },
        { type: 'paragraph', text: ["Apple consistently markets the ", {type: 'interactiveTerm', term: 'User Experience (UX)', definition: 'The overall experience a user has when interacting with a product or service, especially in terms of how easy or pleasing it is to use.'}, " across its entire ", termEcosystem, ". Services like Apple Pay, Apple Music, Fitness+, iCloud, and Apple TV+ are promoted as being seamlessly interconnected, providing users with a cohesive and intuitive experience across all their Apple devices."] },
        { type: 'subheading', text: ["Innovation Driven by Research & Development (R&D)"] },
        { type: 'paragraph', text: ["Substantial investment in ", {type: 'interactiveTerm', term: 'Research & Development (R&D)', definition: 'Activities companies undertake to innovate and introduce new products and services or to improve their existing offerings.'}, " is a cornerstone of Apple's marketing, as it fuels the creation of new and exciting products. Innovations such as the Apple Vision Pro (a VR/AR headset) and Apple's custom-designed silicon chips with advanced ", {type: 'interactiveTerm', term: 'Artificial Intelligence (AI)', definition: 'The simulation of human intelligence processes by machines, especially computer systems. These processes include learning, reasoning, and self-correction.'}, " integration are heavily featured in their promotional activities, highlighting the company's technological leadership."] },
        
        marketingVideoBlock,
        marketingVideoQuizBlock,
        marketingVideoShortAnswers,

        { type: 'heading', text: ["Targeted Marketing Strategies for Services: Apple Music & Apple TV+"] },
        { type: 'subheading', text: "Apple Music:" },
        { type: 'list', items: [
            ["Event Sponsorships: Apple Music leverages high-profile event sponsorships, such as the Super Bowl halftime show, to enhance ", termBranding, " visibility and cultural relevance, associating the service with major entertainment events."],
            ["Curated User Experiences: The service focuses on providing personalized playlists and exclusive content to deeply engage users and differentiate itself from competitors in the crowded music streaming market."]
        ]},
        { type: 'resourceLink', text: "Business of Apps - Apple Music Statistics", url: "https://www.businessofapps.com/data/apple-music-statistics/"},
        { type: 'subheading', text: "Apple TV+:" },
        { type: 'list', items: [
            ["Premium Content Investment: Apple allocates significant budgets to produce high-quality, original content, signaling a commitment to excellence and attracting top-tier talent. This strategy was notably successful with productions like 'CODA' winning the Academy Award for Best Picture.",],
            ["Integrated ", termEcosystem, " Promotion: Apple TV+ benefits from its integration within the broader Apple ", termEcosystem, ". It is often promoted through Apple One subscription bundles, which offer convenience and value, encouraging adoption among existing Apple users."]
        ]},
    ],
    mcqs: [
        { id: 'mk_mcq1', question: "How does Apple primarily market its Apple Watch and AirPods?", options: ["As budget-friendly tech", "As enterprise-focused tools", "As fashionable, health-focused lifestyle products", "As gaming accessories"], correctAnswerIndex: 2, explanation: "Apple positions these wearables as part of a premium lifestyle, emphasizing design, health features, and fashion, rather than just their technical specifications." }
    ],
    shortAnswerPrompts: [
        { id: 'mk_sa1', prompt: "Outline the changes in Apple's marketing approach over time. Identify how these changes impact the four elements of the marketing mix (4Ps: Product, Price, Place, Promotion)." },
        { id: 'mk_sa2', prompt: "Explain how Apple has responded to or managed changes in the marketing landscape (e.g., rise of digital media, shift to services). What specific adjustments have they made to their products, pricing, distribution (place), or promotional strategies?" },
        { id: 'mk_sa3', prompt: "Outline the outcomes of Apple's evolving marketing strategies and evaluate their effectiveness. What evidence suggests success or areas for improvement?" }
    ]
  },
  {
    id: SectionKey.FINANCE,
    title: "Financial Management and Performance",
    summary: "Analyzing Apple's significant revenue growth, net income trends, and strategic financial diversification from hardware to a robust services portfolio.",
    icon: CurrencyDollarIcon,
    detailedContent: [
      { type: 'heading', text: ["Impressive Growth in ", termRevenue, " and ", termNetIncome] },
      { type: 'paragraph', text: ["Apple has demonstrated extraordinary financial growth over the decades. Its total annual ", termRevenue, " surged from approximately $19 billion in 2006 to a staggering $394.33 billion in 2022. Similarly, ", termNetIncome, " (profit) has seen substantial increases, although, like any mature company, it can experience periods of fluctuation. For instance, reports indicated a net income of $93.736 billion in early 2024, which was a slight decline of 3.36% from the previous year, reflecting dynamic market conditions."] },
      { type: 'resourceLink', text: "Apple Net Income (MacroTrends)", url: "https://www.macrotrends.net/stocks/charts/AAPL/apple/net-income" },
      { type: 'subheading', text: ["Strategic ", {type: 'interactiveTerm', term: 'Diversification', definition: 'A corporate strategy to enter into a new market or industry in which the business doesn\'t currently operate, while also creating a new product for that new market.'}, " of Revenue Streams"] },
      { type: 'paragraph', text: ["While the iPhone remains a core product, contributing the majority of sales (around 63%), Apple has strategically diversified its revenue sources to reduce dependence on hardware sales and cultivate more consistent, ", {type: 'interactiveTerm', term: 'recurring revenue', definition: 'The portion of a company\'s revenue that is expected to continue in the future. Unlike one-off sales, recurring revenue is predictable, stable and can be counted on to occur at regular intervals going forward with a high degree of certainty.'}, " streams. Key areas of diversification include:"] },
      { type: 'list', items: [
          ["App Store ", termEcosystem, ": This platform facilitated an estimated $1.1 trillion in billings and sales in 2022. Since 2008, developers have earned over $320 billion. The revenue model is dominated by in-app purchases (approximately 66%) and subscriptions (around 33%)."],
          ["Wearables: Products like the Apple Watch and AirPods have become significant revenue contributors, collectively bringing in over $40 billion annually."],
          ["Services: This fast-growing segment includes Apple Music, Apple TV+, iCloud, and Apple Pay. Apple Music, for example, was projected to have around 124 million subscribers in 2025 and generated $9.2 billion in revenue in 2023. Apple TV+, while having a substantial viewership (estimated 45.9 million in 2025), reportedly incurs annual losses due to high investment costs in original content production."]
      ]},
      { type: 'image', src: 'https://images.unsplash.com/photo-1640653799845-9f30490a4b38?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGZpbmFuY2lhbCUyMGNoYXJ0fGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60', alt: 'Financial chart showing growth', caption: 'Financial charts often illustrate a company\'s growth trajectory and revenue diversification.' },
    ],
     mcqs: [
        { id: 'fin_mcq1', question: "Which of the following is a key part of Apple's strategy to reduce reliance on hardware sales?", options: ["Increasing iPhone prices", "Expanding into car manufacturing", "Diversifying into services and accessories", "Opening more retail stores"], correctAnswerIndex: 2, explanation: "Apple has actively grown its Services (Music, TV+, iCloud) and Wearables (Watch, AirPods) segments to create more diverse and recurring revenue streams, lessening its dependence on cyclical iPhone sales." }
    ],
    shortAnswerPrompts: [
      { id: 'fin_sa1', prompt: ["Outline the significant financial changes Apple has experienced, particularly regarding its ", termRevenue, " sources. How do factors like sales, cost of materials, ", termOperatingExpenses, ", profits, and ", {type: 'interactiveTerm', term: 'cash flow', definition: 'The net amount of cash and cash-equivalents being transferred into and out of a business. Positive cash flow indicates that a company\'s liquid assets are increasing.'}, " reflect these changes?"] },
      { id: 'fin_sa2', prompt: ["Explain how Apple has responded to or managed these financial changes. How do strategies like product ", {type: 'interactiveTerm', term: 'Diversification', definition: 'A corporate strategy to enter into a new market or industry in which the business doesn\'t currently operate, while also creating a new product for that new market.'}, " (e.g., into services) and marketing efforts (e.g., promoting subscriptions) play a role?"] },
      { id: 'fin_sa3', prompt: "Outline the outcomes of Apple's financial strategies and evaluate their effectiveness. To what degree have they successfully managed financial shifts and maintained profitability?" }
    ]
  },
   {
    id: SectionKey.HUMAN_RESOURCES,
    title: "Human Resources Management",
    summary: "Delving into Apple's strategies for attracting, developing, and retaining top talent in a competitive and innovative environment.",
    icon: UsersIcon,
    detailedContent: [
      { type: 'heading', text: ["Attracting Top Talent: Building a Desirable Workplace"] },
      { type: 'list', items: [
        ["Innovation and Mission-Driven ", {type: 'interactiveTerm', term: 'Organizational Culture', definition: 'The collection of values, beliefs, ethics, and attitudes that characterize an organization and guide its practices.'}, ": Apple is renowned for its cutting-edge products and disruptive innovations. This reputation attracts individuals passionate about technology and driven to make a difference. The company's mission, often articulated as 'leaving the world better than we found it,' resonates with employees and motivates them to contribute to positive change."],
        ["Competitive ", {type: 'interactiveTerm', term: 'Compensation and Benefits', definition: 'The combination of salary, wages, and other benefits (such as health insurance, retirement plans, and paid time off) that an employer provides to an employee in exchange for their work.'}, ": To attract and retain premier talent, Apple offers competitive salaries, performance-based bonuses, and stock options. They also provide comprehensive benefits packages, including wellness programs, generous parental leave, and excellent health insurance."]
      ]},
      { type: 'heading', text: ["Employee Development and Retention Strategies"] },
      { type: 'list', items: [
        ["Emphasis on Employee Development and Recognition: Apple invests in its employees by providing opportunities for learning and growth through various training programs and learning resources. They also actively recognize and reward employees for their achievements, fostering a culture of excellence and motivation."],
        ["Focus on Employee Retention: Apple understands that attracting top talent is only part of the equation; retaining that talent is equally crucial. They prioritize employee satisfaction by striving to create a positive work environment where employees feel valued, respected, and have a strong sense of belonging."],
        ["Culture of Top-Notch Excellence: Apple's ", {type: 'interactiveTerm', term: 'Organizational Culture', definition: 'The collection of values, beliefs, ethics, and attitudes that characterize an organization and guide its practices.'}, " emphasizes excellence and continuous improvement. This attracts individuals who are driven to achieve high standards and contributes to the company's history of hiring and developing top-tier talent."]
      ]},
      { type: 'resourceLink', text: "Example: Why Apple is Australia's most attractive employer", url: "https://www.hcamag.com/au/specialisation/employment-law/why-apple-is-australias-most-attractive-employer/407321"},
      { type: 'subheading', text: ["Adapting HR for New Ventures: Streaming Services Case"] },
      { type: 'paragraph', text: ["As Apple expanded into new domains like streaming services (Apple Music and Apple TV+), its Human Resources department had to adapt to recruit new types of talent. This included hiring for specialized roles such as Executive Assistants to support senior management, Software Engineers to build and maintain the streaming platforms, and People Process Analysts to ensure efficient team organization and adherence to company policies. These roles are critical for the smooth operation and success of these service-oriented ventures."] }
    ],
    shortAnswerPrompts: [
      { id: 'hr_sa1', prompt: ["Outline the changes in Apple's business (e.g., growth, diversification into services, technological advancements) and explain how these changes affect its human resources functions, specifically ", {type: 'interactiveTerm', term: 'talent acquisition', definition: 'The process of finding and hiring skilled human labor for organizational needs and to meet any labor requirement.'}, " (recruitment), employee development (training and growth), maintenance (compensation, benefits, employee relations), and separation (turnover, retirement)."] },
      { id: 'hr_sa2', prompt: "Explain how Apple's Human Resources department has responded to or managed these changes. What strategies or initiatives have they implemented to attract, develop, and retain the necessary talent in a dynamic environment?" },
      { id: 'hr_sa3', prompt: "Outline the outcomes of Apple's HR strategies in response to business changes. Evaluate the effectiveness of these strategies in maintaining a skilled, motivated, and adaptable workforce. What are some indicators of their success or areas for improvement?" }
    ]
  },
  {
    id: SectionKey.MANAGEMENT_APPROACHES,
    title: "Management & Leadership Styles at Apple",
    summary: "Analyzing the evolution of Apple's leadership from the autocratic style of Steve Jobs to Tim Cook's more democratic approach, alongside its enduring functional organizational structure.",
    icon: LightBulbIcon,
    detailedContent: [
      { type: 'heading', text: "Leadership Styles: A Tale of Two CEOs" },
      { type: 'paragraph', text: ["Apple's management style has notably evolved under its different CEOs. Founder Steve Jobs was known for an intense, often ", termAutocraticLeadership, " style. He was deeply involved in product details, demanded exceptionally high standards, and was the primary driver of innovation. His vision and control were central to Apple's resurgence and iconic product launches."] },
      { 
        type: 'image', 
        src: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Steve_Jobs_Headshot_2010-CROP2.jpg', 
        alt: 'Steve Jobs, former CEO of Apple', 
        caption: 'Steve Jobs, known for his visionary and often autocratic leadership style.' 
      },
      { type: 'paragraph', text: ["In contrast, the current CEO, Tim Cook, employs a more ", termDemocraticLeadership, " and collaborative approach. He delegates more responsibility to high-ranking executives, fostering a cooperative environment. While still maintaining high standards, Cook's era has also seen an increased emphasis on ", {type: 'interactiveTerm', term: 'Corporate Social Responsibility (CSR)', definition: 'A business model by which companies make a concerted effort to operate in ways that enhance rather than degrade society and the environment.'}, " and environmental sustainability, building upon Jobs' legacy while expanding product lines and entering new markets."] },
      { 
        type: 'image', 
        src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Tim_Cook_EU_Visit_July_2023_%28cropped%29.jpg/800px-Tim_Cook_EU_Visit_July_2023_%28cropped%29.jpg', 
        alt: 'Tim Cook, current CEO of Apple', 
        caption: 'Tim Cook, who adopted a more democratic and collaborative leadership approach.' 
      },
      { type: 'heading', text: ["Organizational Structure: The Functional Approach"] },
      { type: 'paragraph', text: ["Apple is predominantly structured as a ", {type: 'interactiveTerm', term: 'functional organizational structure', definition: 'A common type of organizational structure in which the organization is divided into smaller groups based on specialized functional areas, such as IT, finance, or marketing.'}, ". This means the company is organized around specific functions or areas of expertise (e.g., hardware engineering, software development, marketing, operations). Experts in these respective fields lead their divisions, allowing for deep specialization, accountability, and informed decision-making at all levels. This structure has been a consistent feature of Apple's organization and is seen as contributing to its product excellence and operational efficiency."] },
      { type: 'heading', text: "Enduring Focus on Innovation and Quality" },
      { type: 'paragraph', text: ["Regardless of leadership style, a relentless pursuit of perfection and groundbreaking innovation has remained a core tenet at Apple. This was a hallmark of Steve Jobs' leadership and continues under Tim Cook. A strong emphasis on quality is applied to every product and service Apple offers, forming a key part of its brand identity and customer appeal."] },
      { type: 'heading', text: "The Importance of Collaboration and Communication" },
      { type: 'paragraph', text: ["Despite differences in top leadership styles, Apple values teamwork and collaboration. Managers are expected to be involved in collective decision-making processes. Effective communication is also a key aspect of their management style, with mechanisms like regular feedback sessions and 360-degree performance reviews designed to ensure alignment and continuous improvement across the organization."] },
    ],
    shortAnswerPrompts: [
      { id: 'mgmt_sa1', prompt: "Explain the management approach(es) (e.g., autocratic, democratic, participative) that was, or would be, most effective for Apple in managing specific types of change (e.g., technological innovation, ethical crises, market expansion). Justify your reasoning." }
    ]
  },
  {
    id: SectionKey.INFLATION_IMPACT,
    title: "Navigating the Impact of Inflation",
    summary: "Understanding how macroeconomic factors like inflation affect Apple's costs, pricing strategies, and consumer demand in a global market.",
    icon: PresentationChartLineIcon,
    detailedContent: [
      { type: 'heading', text: ["Understanding ", termInflation, " and its Pressures on Apple"] },
      { type: 'paragraph', text: [termInflation, ", the rate at which general price levels rise and ", {type: 'interactiveTerm', term: 'purchasing power', definition: 'The value of a currency expressed in terms of the amount of goods or services that one unit of money can buy.'}, " falls, poses several challenges for global companies like Apple. The company faces increasing costs from various sources, including global ", {type: 'interactiveTerm', term: 'logistics', definition: 'The overall process of managing how resources are acquired, stored, and transported to their final destination. It involves planning, implementing, and controlling procedures for the efficient and effective transportation and storage of goods.'}, ", rising employee salaries to remain competitive, and shortages of critical components like silicon chips. For example, in May 2022, the annual inflation rate in the U.S. reached 8.6%, a multi-decade high, with similar trends observed in other major markets for Apple."] },
      { type: 'subheading', text: ["Impact on Apple's Financial Health (Balance Sheet)"] },
      { type: 'list', items: [
        [termGrossMargin, ": Rising costs of components and manufacturing can squeeze Apple's ", termGrossMargin, ". While Apple's margins, such as the reported 43.7% in Q1 2022, have historically been strong, they are not immune to inflationary pressures."],
        [termOperatingExpenses, ": These have increased due to higher freight charges for shipping components and finished goods globally, as well as increased labor costs. Apple, for instance, proactively lifted pay for its corporate and retail employees in response to market conditions and inflation."]
      ]},
      { type: 'heading', text: "Apple's Strategic Responses to Inflationary Pressures" },
      { type: 'list', items: [
        ["Selective Pricing Adjustments: Apple dynamically adjusts its pricing in different countries in response to ", {type: 'interactiveTerm', term: 'currency fluctuations', definition: 'Changes in the value of one currency in relation to another. These fluctuations can impact the profitability of international sales.'}, " and local market conditions. It has, at times, raised prices for its flagship products selectively (e.g., the iPhone 12's launch price was higher than its predecessor in some markets, and iPhone 13 prices saw increases in Japan due to currency shifts)."],
        ["Absorbing Costs: In some instances, particularly for its core products in key markets, Apple might choose to absorb some of the increased costs to maintain price stability and avoid deterring demand, even if it means a temporary hit to its ", termGrossMargin, "."],
        ["Product Pricing Structure Reviews: With new product launches, Apple has the opportunity to reassess and adjust its overall product pricing structure to reflect current economic realities and component costs."]
      ]},
      { type: 'heading', text: "Impact on Consumer Demand and Market Dynamics" },
      { type: 'paragraph', text: ["A significant risk during inflationary periods is the potential for slowing sales, as consumers with reduced ", {type: 'interactiveTerm', term: 'purchasing power', definition: 'The value of a currency expressed in terms of the amount of goods or services that one unit of money can buy.'}, " might delay discretionary purchases like smartphone upgrades. However, Apple's customer base, which often consists of consumers with higher disposable incomes, has historically shown more resilience to economic downturns compared to the broader market. Apple continues to dominate the 'ultra-premium' smartphone segment (devices priced over $1,000), where demand can be less sensitive to general economic pressures."] },
      { type: 'resourceLink', text: "CNN Article: How inflation will affect Apple", url: "https://www.cnn.com/2022/07/01/tech/apple-inflation/index.html" }
    ],
  },
  {
    id: SectionKey.EFFECTIVENESS_EVALUATION,
    title: "Evaluating Apple's Change Management Effectiveness",
    summary: "Providing a framework and key considerations for assessing the overall success of Apple's strategies in managing various business changes.",
    icon: SparklesIcon,
    detailedContent: [
      { type: 'heading', text: ["A Framework for Evaluating ", termChangeManagement, " Success"] },
      { type: 'paragraph', text: ["Evaluating the effectiveness of Apple's ", termChangeManagement, " requires a multi-faceted approach. It's not just about whether a change was implemented, but how well it achieved its ", {type: 'interactiveTerm', term: 'strategic objectives', definition: 'The long-term goals that an organization aims to achieve. These objectives guide the company’s direction and resource allocation.'}, ", its impact on financial performance, its influence on market position, the satisfaction of key ", {type: 'interactiveTerm', term: 'stakeholders', definition: 'Any individual, group, or organization that can affect or is affected by an organization\'s actions, objectives, and policies. Examples include customers, employees, investors, suppliers, and the community.'}, " (including customers, employees, and investors), and the company's enhanced ability to adapt to future changes."] },
      { type: 'subheading', text: "Key Questions to Guide Your Evaluation:" },
      { type: 'list', items: [
        ["Financial Performance: How have specific changes (e.g., ", termOutsourcing, ", diversification into services) impacted Apple's ", termRevenue, ", ", termNetIncome, ", ", termGrossMargin, ", and stock value over time?"],
        ["Market Leadership & Position: Has Apple maintained or strengthened its leadership in key product categories (e.g., smartphones, wearables, tablets) despite the changes and competitive pressures?"],
        ["Innovation and Product Development: How successful has Apple been in continuously launching innovative new products and services that meet or create market demand?"],
        ["Operational Efficiency & ", termSupplyChain, " Resilience: Have changes like ", termOutsourcing, " and ", termSupplyChain, " modifications led to sustained cost savings, improved efficiency, and better resilience against disruptions?"],
        ["Brand Reputation & Trust: How effectively has Apple managed ethical challenges (e.g., in its ", termSupplyChain, ") and maintained or enhanced its ", termBranding, " image and customer trust?"],
        ["Employee Satisfaction & Talent Retention: What has been the impact of organizational changes and HR strategies on company culture, employee morale, and the ability to retain top talent?"],
        ["Customer Loyalty & Satisfaction: How have Apple's changes in products, services, and ", {type: 'interactiveTerm', term: 'User Experience (UX)', definition: 'The overall experience a user has when interacting with a product or service, especially in terms of how easy or pleasing it is to use.'}, " affected customer satisfaction levels and loyalty?"],
        ["Sustainability Goals & ", {type: 'interactiveTerm', term: 'Corporate Social Responsibility (CSR)', definition: 'A business model by which companies make a concerted effort to operate in ways that enhance rather than degrade society and the environment.'}, ": Is Apple making tangible progress towards its stated environmental commitments (e.g., becoming ", termCarbonNeutral, ") and fulfilling its broader social responsibilities?"]
      ]},
      { type: 'paragraph', text: ["Evidence for your evaluation can be gathered from various sources, including Apple's official financial reports and investor briefings, market share data from reputable analysts, customer satisfaction surveys and reviews, employee feedback and retention statistics, sustainability reports, and media coverage of successful product launches and company initiatives. Consider both quantitative data (numbers, figures) and qualitative data (opinions, descriptions) for a balanced assessment."] },
    ],
    shortAnswerPrompts: [
      { id: 'eval_sa1', prompt: ["Evaluate the overall effectiveness of Apple’s ", termChangeManagement, " strategies in response to the various influences discussed (technological, economic, social, ethical). To what degree has Apple been successful in adapting and thriving? What specific evidence supports your assessment of their successes and any potential shortcomings?"] }
    ]
  },
];
